#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

if [ "$1" == -r ]; then
	m 'building binaries (WASI release)...' "$CYAN"
	cargo build --package=compris-cli --target=wasm32-wasip2 --release
else
	m 'building binaries (WASI dev)...' "$CYAN"
	cargo build --package=compris-cli --target=wasm32-wasip2
fi

m 'to run' "$GREEN"
m 'wasmtime --dir . --wasi inherit-network=y --wasi http=y target/wasm32-wasip2/debug/compris.wasm'
