#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

if [ "$TARGET" == release ]; then
	cargo install --path="$ROOT/crates/cli" --release
else
	cargo install --path="$ROOT/crates/cli"
fi
