#!/bin/bash
set -e

HERE=$(dirname "$(readlink --canonicalize "$BASH_SOURCE")")
. "$HERE/_env"

cd "$ROOT"

#cargo expand --package=compris "$@"
cargo expand --example resolve_enum -p compris --features=derive
